backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "ProductPage"
    label: "Product Page"
    folder: "src/pages/product_page"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product_page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Hero Image", name: "heroImage", widget: "image"}
      - {label: Summary, name: summary, widget: object, fields: [
          {label: Duration, name: duration, widget: string}, 
          {label: Location, name: location, widget: string},
          {label: Group Size, name: groupSize, widget: string}, 
          {label: Annual Leave, name: annualLeave, widget: string}, 
          {label: Accomodation, name: accomodation, widget: string},
          {label: Meeting Point, name: meetingPoint, widget: string},
          {label: Fitness Level, name: fitnessLevel, widget: string},
        ]}
      - {label: "Activities", name: "activities", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
